stages:
  - test
  
test:
  variables:
    SECURE_FILES_DOWNLOAD_PATH: './where/files/should/go/'
  script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - ls where/files/should/go/
    - curl --header "PRIVATE-TOKEN:glpat-PH3fib_xYsKxR4mvMmCH" "https://gitlab.com/api/v4/projects/1/secure_files"
    - curl --request POST --header "PRIVATE-TOKEN:glpat-PH3fib_xYsKxR4mvMmCH" \
     "https://gitlab.com/api/v4/projects/1/secure_files"  --form "name=README.md" --form "file=.@/path/to/file/README.md"



